services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - llm
      - adminpanel
      - apidb
    networks:
      - dev

  llm:
    build:
      context: ./llmapi
    networks:
      - dev

  adminpanel:
    build:
      context: ./sky-admin
    networks:
      - dev

  apidb:
    build:
      context: ./SkyServer
    networks:
      - dev

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: SkyServer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    networks:
      - dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
        
networks:
  dev:

volumes:
  postgres_data: # Declares the named volume