networks:
  dev:

  services:
    nginx:
      image: nginx:stable-alpine
      ports:
        - "80:80"
      volumes:
        - './nginx.conf:/etc/nginx/nginx.conf'
      depends_on:
        - llm
        - admin-panel
        - apidb
      networks:
        - dev

    llm:
      build:
        context: ./llmapi
      networks:
        - dev

    admin-panel:
      build:
        context: ./sky-admin
      networks:
        - dev
    
    apidb:
      build:
        context: ./SkyServer
      networks:
        - dev